AWSTemplateFormatVersion: "2010-09-09"
Resources:
 S3Bucket:
  Type: "AWS::S3::Bucket"
  Properties:
   AccessControl: Private
   BucketName: bucketforcust
   AccelerateConfiguration:
    AccelerationStatus: Enabled
   PublicAccessBlockConfiguration:
    BlockPublicAcls: true
    IgnorePublicAcls: true
